sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shivam123425/react-tests -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true shivam123425/react-tests npm run test -- --coverage

after_success:
  - docker build -t shivam123425/multi-worker ./worker
  - docker build -t shivam123425/multi-client ./client
  - docker build -t shivam123425/multi-nginx ./nginx
  - docker build -t shivam123425/multi-server ./server

  #login to docker with password and id from environment var added in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  #push built images to docker hub
  - docker push shivam123425/multi-worker
  - docker push shivam123425/multi-client
  - docker push shivam123425/multi-nginx
  - docker push shivam123425/multi-server

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: multi-container-app
  env: MultiContainerApp-env
  bucket_name: elasticbeanstalk-us-east-1-054252703049
  bucket_path: docker-multi-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY